# DEV ONLY
from pathlib import Path

import m2cgen as m2c
import numpy as np
import pandas as pd
import xgboost as xgb

BASE_PATH = Path("datasets")


def load_and_harmonize_datasets():
    dfs = []

    kaggle_path = Path.joinpath(BASE_PATH, "student_data.csv")
    if kaggle_path.exists():
        df_k = pd.read_csv(kaggle_path)
        df_k_norm = pd.DataFrame(
            {
                "DailyStudyHours": df_k["StudyTimeWeekly"] / 7.0,
                "Absences": df_k["Absences"],
                "AcademicGrade": df_k["GPA"] * 5.0,
                "PastFailures": (df_k["GPA"] < 2.0).astype(int),
                "SupportLevel": df_k["Tutoring"] * 2 + df_k["ParentalSupport"],
                "Source": "Kaggle",
            }
        )
        dfs.append(df_k_norm)
        print(f"Kaggle Dataset: {len(df_k_norm)} rows")
    else:
        print("'student_data.csv' not found. Skipping...")

    uci_mat_path = Path.joinpath(BASE_PATH, "student-mat.csv")
    if uci_mat_path.exists():
        df_mat = pd.read_csv(uci_mat_path, sep=";")
        studytime_hours = df_mat["studytime"].map({1: 1.5, 2: 3.5, 3: 7.5, 4: 12.0})
        support = (
            (df_mat["schoolsup"] == "yes").astype(int)
            + (df_mat["famsup"] == "yes").astype(int)
            + (df_mat["paid"] == "yes").astype(int) * 2
        )
        df_mat_norm = pd.DataFrame(
            {
                "DailyStudyHours": studytime_hours / 7.0,
                "Absences": df_mat["absences"],
                "AcademicGrade": df_mat["G3"],
                "PastFailures": df_mat["failures"],
                "SupportLevel": support,
                "Source": "UCI_Math",
            }
        )
        dfs.append(df_mat_norm)
        print(f"UCI Math Dataset: {len(df_mat_norm)} rows")
    else:
        print("'student-mat.csv' not found. Skipping...")

    uci_por_path = Path.joinpath(BASE_PATH, "student-por.csv")
    if uci_por_path.exists():
        df_por = pd.read_csv(uci_por_path, sep=";")
        studytime_hours = df_por["studytime"].map({1: 1.5, 2: 3.5, 3: 7.5, 4: 12.0})
        support = (
            (df_por["schoolsup"] == "yes").astype(int)
            + (df_por["famsup"] == "yes").astype(int)
            + (df_por["paid"] == "yes").astype(int) * 2
        )
        df_por_norm = pd.DataFrame(
            {
                "DailyStudyHours": studytime_hours / 7.0,
                "Absences": df_por["absences"],
                "AcademicGrade": df_por["G3"],
                "PastFailures": df_por["failures"],
                "SupportLevel": support,
                "Source": "UCI_Por",
            }
        )
        dfs.append(df_por_norm)
        print(f"Portuguese Dataset: {len(df_por_norm)} rows")
    else:
        print("'student-por.csv' not found. Skipping...")

    if not dfs:
        raise FileNotFoundError(
            "❌ Error: No datasets found! Please place CSV files in project root."
        )

    master_df = pd.concat(dfs, ignore_index=True)
    print(f"Combined Dataset: {len(master_df)} total!")
    return master_df


def train_and_export():
    df = load_and_harmonize_datasets()
    conditions = [
        (df["AcademicGrade"] < 10.0) | (df["Absences"] >= 12) | (df["PastFailures"] >= 2),
        (df["AcademicGrade"] < 14.0) | (df["Absences"] >= 6) | (df["PastFailures"] == 1),
    ]
    choices = [2, 1]
    df["RiskLevel"] = np.select(conditions, choices, default=0)
    counts = df["RiskLevel"].value_counts().to_dict()
    print(
        f"Risk Distribution -> Low (0): {counts.get(0, 0)}, Medium (1): {counts.get(1, 0)}, High (2): {counts.get(2, 0)}"
    )

    feature_cols = ["DailyStudyHours", "Absences", "AcademicGrade", "PastFailures", "SupportLevel"]
    X = df[feature_cols]
    y = df["RiskLevel"]

    print("Training...")
    model = xgb.XGBRegressor(
        n_estimators=25, max_depth=3, learning_rate=0.08, random_state=42, base_score=0.5
    )
    model.fit(X, y)

    print("Exporting model via m2cgen...")
    python_code = m2c.export_to_python(model)

    output_path = Path("src/models/model_inference.py")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED BY m2cgen - DO NOT EDIT MANUALLY\n")
        f.write(python_code)

    print(f"SUCCESS!'{output_path}'.")


if __name__ == "__main__":
    train_and_export()
