# AUTO-GENERATED BY m2cgen - DO NOT EDIT MANUALLY
def score(input):
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var0 = 0.11947598
            else:
                var0 = 0.04129899
        else:
            if input[1] < 6.0:
                var0 = -0.03936731
            else:
                var0 = 0.039759032
    else:
        var0 = 0.11992424
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var1 = 0.10995964
            else:
                var1 = 0.037998773
        else:
            if input[1] < 6.0:
                var1 = -0.03622346
            else:
                var1 = 0.03659747
    else:
        var1 = 0.11033635
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var2 = 0.10120127
            else:
                var2 = 0.03496227
        else:
            if input[1] < 6.0:
                var2 = -0.033330675
            else:
                var2 = 0.033687312
    else:
        var2 = 0.101515025
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var3 = 0.093140535
            else:
                var3 = 0.032168422
        else:
            if input[1] < 6.0:
                var3 = -0.030668907
            else:
                var3 = 0.031008562
    else:
        var3 = 0.09339894
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var4 = 0.08572183
            else:
                var4 = 0.029597828
        else:
            if input[1] < 6.0:
                var4 = -0.028219707
            else:
                var4 = 0.028542822
    else:
        var4 = 0.08593175
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var5 = 0.07889403
            else:
                var5 = 0.027232654
        else:
            if input[1] < 6.0:
                var5 = -0.025966099
            else:
                var5 = 0.026273154
    else:
        var5 = 0.079061545
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var6 = 0.072610065
            else:
                var6 = 0.025056481
        else:
            if input[1] < 6.0:
                var6 = -0.023892459
            else:
                var6 = 0.024183964
    else:
        var6 = 0.072740614
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var7 = 0.066826634
            else:
                var7 = 0.023054209
        else:
            if input[1] < 6.0:
                var7 = -0.021984423
            else:
                var7 = 0.0222609
    else:
        var7 = 0.06692504
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var8 = 0.061503854
            else:
                var8 = 0.021211939
        else:
            if input[1] < 6.0:
                var8 = -0.02022876
            else:
                var8 = 0.020490756
    else:
        var8 = 0.061574414
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var9 = 0.056605022
            else:
                var9 = 0.019516885
        else:
            if input[1] < 6.0:
                var9 = -0.018613303
            else:
                var9 = 0.01886137
    else:
        var9 = 0.056651566
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var10 = 0.052096404
            else:
                var10 = 0.017957283
        else:
            if input[1] < 6.0:
                var10 = -0.017126855
            else:
                var10 = 0.017361552
    else:
        var10 = 0.052122302
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var11 = 0.04794689
            else:
                var11 = 0.016522309
        else:
            if input[1] < 6.0:
                var11 = -0.015759114
            else:
                var11 = 0.015980998
    else:
        var11 = 0.047955144
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var12 = 0.04412789
            else:
                var12 = 0.015202007
        else:
            if input[1] < 6.0:
                var12 = -0.014500601
            else:
                var12 = 0.014710218
    else:
        var12 = 0.044121154
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var13 = 0.04061307
            else:
                var13 = 0.01398721
        else:
            if input[1] < 6.0:
                var13 = -0.013342591
            else:
                var13 = 0.013540487
    else:
        var13 = 0.04059369
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var14 = 0.037378214
            else:
                var14 = 0.0128694875
        else:
            if input[1] < 6.0:
                var14 = -0.01227706
            else:
                var14 = 0.012463772
    else:
        var14 = 0.03734824
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var15 = 0.034401014
            else:
                var15 = 0.011841084
        else:
            if input[1] < 6.0:
                var15 = -0.0112966215
            else:
                var15 = 0.011472679
    else:
        var15 = 0.034362264
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var16 = 0.031660948
            else:
                var16 = 0.01089486
        else:
            if input[1] < 6.0:
                var16 = -0.01039448
            else:
                var16 = 0.0105603915
    else:
        var16 = 0.031615015
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var17 = 0.029139135
            else:
                var17 = 0.010024248
        else:
            if input[1] < 6.0:
                var17 = -0.009564383
            else:
                var17 = 0.00972065
    else:
        var17 = 0.029087411
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[2] < 10.0:
                var18 = 0.026818182
            else:
                var18 = 0.009223206
        else:
            if input[1] < 6.0:
                var18 = -0.008800576
            else:
                var18 = 0.008947684
    else:
        var18 = 0.026761886
    if input[1] < 12.0:
        if input[2] < 14.0:
            if input[3] < 2.0:
                var19 = 0.010295468
            else:
                var19 = 0.041971684
        else:
            if input[1] < 6.0:
                var19 = -0.008097768
            else:
                var19 = 0.008236183
    else:
        var19 = 0.024622288
    if input[2] < 11.0:
        if input[2] < 10.0:
            var20 = 0.022787435
        else:
            if input[3] < 2.0:
                var20 = 0.012615886
            else:
                var20 = 0.07005654
    else:
        if input[1] < 12.0:
            if input[3] < 2.0:
                var20 = 0.0007675528
            else:
                var20 = 0.0925538
        else:
            var20 = 0.022548119
    if input[2] < 13.998348:
        if input[1] < 12.0:
            if input[2] < 10.0:
                var21 = 0.02163758
            else:
                var21 = 0.007265159
        else:
            var21 = 0.02088986
    else:
        if input[1] < 6.0:
            if input[3] < 1.0:
                var21 = -0.008049475
            else:
                var21 = 0.096378736
        else:
            if input[1] < 12.0:
                var21 = 0.0075202263
            else:
                var21 = 0.01995707
    if input[2] < 11.0:
        if input[3] < 1.0:
            if input[2] < 9.055778:
                var22 = 0.020065099
            else:
                var22 = 0.010841784
        else:
            if input[3] < 2.0:
                var22 = 0.019005353
            else:
                var22 = 0.029976206
    else:
        if input[1] < 12.0:
            if input[3] < 2.0:
                var22 = 0.0006108558
            else:
                var22 = 0.08352284
        else:
            var22 = 0.019100156
    if input[2] < 14.0:
        if input[1] < 12.0:
            if input[3] < 2.0:
                var23 = 0.00767204
            else:
                var23 = 0.03174832
        else:
            var23 = 0.017739892
    else:
        if input[1] < 6.0:
            if input[3] < 1.0:
                var23 = -0.007480682
            else:
                var23 = 0.08678399
        else:
            if input[1] < 12.0:
                var23 = 0.006873663
            else:
                var23 = 0.016968342
    if input[2] < 14.0:
        if input[1] < 12.0:
            if input[3] < 2.0:
                var24 = 0.0070588524
            else:
                var24 = 0.02925638
        else:
            var24 = 0.01632161
    else:
        if input[1] < 6.0:
            if input[3] < 1.0:
                var24 = -0.006883283
            else:
                var24 = 0.0821555
        else:
            if input[1] < 12.0:
                var24 = 0.006327082
            else:
                var24 = 0.015669892
    return 0.5 + (var0 + var1 + var2 + var3 + var4 + var5 + var6 + var7 + var8 + var9 + var10 + var11 + var12 + var13 + var14 + var15 + var16 + var17 + var18 + var19 + var20 + var21 + var22 + var23 + var24)
